[workspace]
resolver = "2"

members = [
  "cplex-rs",
  "cplex-rs-sys",
]

[workspace.package]
authors = ["Matteo Biggio"]
version = "0.1.9"
license = "MIT OR Apache-2.0"
edition = "2021"
keywords = ["optimization", "binding", "cplex"]
repository = "https://github.com/cplex-rs/cplex-rs"
